name: autoupdate
on:
  # pull_request:
  #   types:
  #     - labeled
  #     - unlabeled
  #     - synchronize
  #     - opened
  #     - edited
  #     - ready_for_review
  #     - unlocked
  #     - reopened
  push:
    branches:
      - 'main'
      - 'master'
#    tags: {}

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: autoupdate
        uses: ./
